trigger:
- main  # Replace 'main' with the appropriate branch trigger

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: DeployCloudFormation
    steps:
          
    - task: CloudFormationCreateOrUpdateStack@1
      inputs:
        awsCredentials: 'awsmastercred'
        regionName: 'us-west-1'
        stackName: 'test1222'
        templateSource: 'usePrevious'
        templateParametersSource: 'inline'
        templateParameters: |
          - ParameterKey: deploymentID
             ParameterValue: $(deploymentID)
           - ParameterKey: InstanceType
              ParameterValue: $(InstanceType)

    
    # Set an output variable for stackName
    - script: echo "##vso[task.setvariable variable=stackName;isOutput=true]$(stackName)"
      displayName: 'Set Stack Name Output Variable'
