trigger:
- main  # Or your specific branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  stackName: 'MyCloudFormationStack'
  deploymentID: '12345'
  InstanceType: 't3.micro'

stages:
- stage: Deploy
  jobs:
  - job: DeployCloudFormation
    steps:
    - checkout: self  # Ensures code from repo is available

    

  
    - task: CloudFormationCreateOrUpdateStack@1
      inputs:
        awsCredentials: 'awsgovcloud'
        regionName: 'us-gov-west-1'
        stackName: 'test1234'
        templateSource: 'url'
        templateUrl: 'https://csc-bucket.s3.us-gov-east-1.amazonaws.com/awsgovcloud.json'
        templateParametersSource: 'inline'
        templateParameters: |
          - ParameterKey: deploymentID
             ParameterValue: $(deploymentID)
           - ParameterKey: InstanceType
              ParameterValue: $(InstanceType)

    - script: echo "##vso[task.setvariable variable=stackName;isOutput=true]$(stackName)"
      displayName: 'Set Stack Name Output Variable'       
      