trigger:
- main  # Replace 'main' with the appropriate branch trigger

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: DeployCloudFormation
    steps:
    - task: CloudFormationCreateOrUpdateStack@1
      displayName: 'Create or Update CloudFormation Stack'
      inputs:
        awsCredentials: $(service-connection)
        regionName: 'us-gov-west-1'
        stackName: $(stackName)  # Define the stackName parameter here
        templateSource: 'url'
        templateUrl: 'https://csc-bucket.s3.us-gov-east-1.amazonaws.com/fullvpcscenario.json'
        templateParametersSource: 'inline'
        templateParameters: |
          - ParameterKey: deploymentID
            ParameterValue: $(deploymentID)
          - ParameterKey: InstanceType
            ParameterValue: $(InstanceType)
    
    # Set an output variable for stackName
    - script: echo "##vso[task.setvariable variable=stackName;isOutput=true]$(stackName)"
      displayName: 'Set Stack Name Output Variable'
